begin;
create table if not exists public.user_profiles(id uuid primary key references auth.users(id) on delete cascade,first_name text,last_name text,role text not null default 'Viewer' check(role in('Super Administrator','Administrator','Operations Manager','Analyst','Viewer')),department text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create or replace function public.set_user_profile_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists set_user_profile_updated_at on public.user_profiles; create trigger set_user_profile_updated_at before update on public.user_profiles for each row execute function public.set_user_profile_updated_at();
create or replace function public.create_profile_for_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.user_profiles(id,first_name,last_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'first_name',new.raw_user_meta_data->>'given_name'),coalesce(new.raw_user_meta_data->>'last_name',new.raw_user_meta_data->>'family_name'),'Viewer') on conflict(id) do nothing; return new; end $$;
drop trigger if exists create_profile_after_auth_user on auth.users; create trigger create_profile_after_auth_user after insert on auth.users for each row execute function public.create_profile_for_new_auth_user();
alter table public.user_profiles enable row level security;
drop policy if exists "Users can read their own profile" on public.user_profiles; create policy "Users can read their own profile" on public.user_profiles for select to authenticated using(auth.uid()=id);
drop policy if exists "Users can create their own profile" on public.user_profiles; create policy "Users can create their own profile" on public.user_profiles for insert to authenticated with check(auth.uid()=id and role='Viewer');
drop policy if exists "Users can update their own profile" on public.user_profiles; create policy "Users can update their own profile" on public.user_profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);
grant select,insert,update on public.user_profiles to authenticated; revoke all on public.user_profiles from anon;
commit; notify pgrst,'reload schema';
