import {createContext,useCallback,useEffect,useMemo,useState,type ReactNode} from 'react'
import type {Session,User} from '@supabase/supabase-js'
import {supabase} from '../lib/supabase'
export type UserProfile={id:string;first_name:string|null;last_name:string|null;role:string;department:string|null}
type AuthValue={user:User|null;session:Session|null;profile:UserProfile|null;loading:boolean;login:(e:string,p:string)=>Promise<void>;logout:()=>Promise<void>;requestPasswordReset:(e:string)=>Promise<void>;updatePassword:(p:string)=>Promise<void>;refreshProfile:()=>Promise<void>}
export const AuthContext=createContext<AuthValue|undefined>(undefined)
const origin=()=>import.meta.env.DEV?window.location.origin:'https://ivm.theburrowfarm.com'
async function ensureProfile(user:User){const found=await supabase.from('user_profiles').select('*').eq('id',user.id).maybeSingle();if(found.error)throw found.error;if(found.data)return found.data as UserProfile;const m=user.user_metadata??{};const created=await supabase.from('user_profiles').insert({id:user.id,first_name:m.first_name??m.given_name??null,last_name:m.last_name??m.family_name??null,role:'Viewer',department:null}).select('*').single();if(created.error){if(created.error.code==='23505'){const retry=await supabase.from('user_profiles').select('*').eq('id',user.id).single();if(retry.error)throw retry.error;return retry.data as UserProfile}throw created.error}return created.data as UserProfile}
export function AuthProvider({children}:{children:ReactNode}){const[session,setSession]=useState<Session|null>(null);const[profile,setProfile]=useState<UserProfile|null>(null);const[loading,setLoading]=useState(true);const load=useCallback(async(user:User|null)=>{if(!user){setProfile(null);return}try{setProfile(await ensureProfile(user))}catch(e){console.error(e);setProfile(null)}},[]);useEffect(()=>{let active=true;supabase.auth.getSession().then(async({data,error})=>{if(error)console.error(error);if(!active)return;setSession(data.session??null);await load(data.session?.user??null);if(active)setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);queueMicrotask(async()=>{await load(s?.user??null);if(active)setLoading(false)})});return()=>{active=false;subscription.unsubscribe()}},[load]);const login=useCallback(async(e:string,p:string)=>{const{error}=await supabase.auth.signInWithPassword({email:e.trim(),password:p});if(error)throw error},[]);const logout=useCallback(async()=>{const{error}=await supabase.auth.signOut();if(error)throw error},[]);const requestPasswordReset=useCallback(async(e:string)=>{const{error}=await supabase.auth.resetPasswordForEmail(e.trim(),{redirectTo:`${origin()}/reset-password`});if(error)throw error},[]);const updatePassword=useCallback(async(p:string)=>{const{error}=await supabase.auth.updateUser({password:p});if(error)throw error},[]);const refreshProfile=useCallback(async()=>load(session?.user??null),[load,session?.user]);const value=useMemo(()=>({user:session?.user??null,session,profile,loading,login,logout,requestPasswordReset,updatePassword,refreshProfile}),[session,profile,loading,login,logout,requestPasswordReset,updatePassword,refreshProfile]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
