begin;

alter table if exists public.user_profiles
  add column if not exists email text,
  add column if not exists status text not null default 'active',
  add column if not exists last_login_at timestamptz,
  add column if not exists disabled_at timestamptz,
  add column if not exists locked_at timestamptz,
  add column if not exists invitation_accepted_at timestamptz;

create table if not exists public.user_invitations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'Viewer',
  department text,
  status text not null default 'pending' check (status in ('pending','accepted','expired','revoked')),
  invited_by uuid references auth.users(id) on delete set null,
  expires_at timestamptz not null default (now() + interval '72 hours'),
  accepted_at timestamptz,
  resend_message_id text,
  last_sent_at timestamptz,
  send_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_ivm_admin() returns boolean
language sql stable security definer set search_path=public as $$
  select exists (
    select 1 from public.user_profiles
    where id=auth.uid() and status='active'
      and role in ('Super Administrator','Administrator')
  );
$$;

alter table public.user_invitations enable row level security;
alter table public.user_audit_log enable row level security;

drop policy if exists "Admins manage invitations" on public.user_invitations;
create policy "Admins manage invitations" on public.user_invitations
for all to authenticated using (public.is_ivm_admin()) with check (public.is_ivm_admin());

drop policy if exists "Admins read audit" on public.user_audit_log;
create policy "Admins read audit" on public.user_audit_log
for select to authenticated using (public.is_ivm_admin());

drop policy if exists "Admins read profiles" on public.user_profiles;
create policy "Admins read profiles" on public.user_profiles
for select to authenticated using (auth.uid()=id or public.is_ivm_admin());

commit;
notify pgrst, 'reload schema';
