import { useEffect, useMemo, useState } from 'react'
import { inviteUser, listManagedUsers, manageUser } from '../services/userAdministration'
import type { ManagedUser, UserRole } from '../types/users'

const roles: UserRole[] = ['Super Administrator','Administrator','Operations Manager','Analyst','Viewer']
export default function UsersAccess(){
 const [users,setUsers]=useState<ManagedUser[]>([]), [loading,setLoading]=useState(true), [open,setOpen]=useState(false), [error,setError]=useState(''), [message,setMessage]=useState('')
 const [form,setForm]=useState({email:'',firstName:'',lastName:'',role:'Viewer' as UserRole,department:''})
 async function load(){ setLoading(true); try{ setUsers(await listManagedUsers()) }catch(e){ setError(e instanceof Error?e.message:'Unable to load users') }finally{setLoading(false)} }
 useEffect(()=>{void load()},[])
 const metrics=useMemo(()=>({total:users.length,active:users.filter(x=>x.status==='active').length,pending:users.filter(x=>x.status==='pending_invitation').length,locked:users.filter(x=>x.status==='locked').length}),[users])
 async function submit(e:React.FormEvent){e.preventDefault();setError('');try{await inviteUser(form);setMessage(`Invitation sent to ${form.email}`);setOpen(false);await load()}catch(x){setError(x instanceof Error?x.message:'Invitation failed')}}
 async function act(u:ManagedUser,action:string){if(action==='delete'&&!confirm(`Delete ${u.email}?`))return;try{await manageUser({action,userId:u.id});await load()}catch(x){setError(x instanceof Error?x.message:'Action failed')}}
 return <main className="space-y-6 p-6"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Users & Access</h1><p className="text-sm text-slate-500">Manage invitations, roles, and account status.</p></div><button className="rounded-xl bg-blue-600 px-4 py-2 text-white" onClick={()=>setOpen(true)}>Invite User</button></header>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(metrics).map(([k,v])=><div key={k} className="rounded-2xl border bg-white p-5"><p className="text-sm capitalize text-slate-500">{k}</p><p className="text-3xl font-bold">{v}</p></div>)}</section>
 {message&&<div className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-red-800">{error}</div>}
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full"><thead><tr className="border-b bg-slate-50 text-left"><th className="p-4">User</th><th className="p-4">Department</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{loading?<tr><td className="p-4" colSpan={5}>Loading…</td></tr>:users.map(u=><tr key={u.id} className="border-b"><td className="p-4"><b>{[u.first_name,u.last_name].filter(Boolean).join(' ')||'Unnamed User'}</b><div className="text-sm text-slate-500">{u.email}</div></td><td className="p-4">{u.department||'—'}</td><td className="p-4">{u.role}</td><td className="p-4">{u.status.replaceAll('_',' ')}</td><td className="p-4"><div className="flex flex-wrap gap-2"><button className="rounded border px-2 py-1" onClick={()=>act(u,u.status==='locked'?'unlock':'lock')}>{u.status==='locked'?'Unlock':'Lock'}</button><button className="rounded border px-2 py-1" onClick={()=>act(u,u.status==='disabled'?'enable':'disable')}>{u.status==='disabled'?'Enable':'Disable'}</button><button className="rounded border px-2 py-1" onClick={()=>act(u,'reset_password')}>Reset Password</button><button className="rounded border border-red-200 px-2 py-1 text-red-700" onClick={()=>act(u,'delete')}>Delete</button></div></td></tr>)}</tbody></table></div>
 {open&&<div className="fixed inset-0 z-50 bg-black/30" onClick={()=>setOpen(false)}><aside className="ml-auto h-full w-full max-w-xl bg-white p-7" onClick={e=>e.stopPropagation()}><h2 className="text-xl font-bold">Invite User</h2><form className="mt-6 space-y-4" onSubmit={submit}><input required type="email" placeholder="Email" className="w-full rounded-xl border p-3" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><div className="grid grid-cols-2 gap-3"><input placeholder="First name" className="rounded-xl border p-3" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><input placeholder="Last name" className="rounded-xl border p-3" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></div><select className="w-full rounded-xl border p-3" value={form.role} onChange={e=>setForm({...form,role:e.target.value as UserRole})}>{roles.map(r=><option key={r}>{r}</option>)}</select><input placeholder="Department" className="w-full rounded-xl border p-3" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/><button className="w-full rounded-xl bg-blue-600 p-3 font-semibold text-white">Send Invitation</button></form></aside></div>}</main>
}
